create extension if not exists pgcrypto;

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 40),
  paid boolean not null default false,
  champion_pick text check (char_length(champion_pick) <= 40),
  top_scorer_pick text check (char_length(top_scorer_pick) <= 60),
  runner_up_pick text check (char_length(runner_up_pick) <= 40),
  finalist_one_pick text check (char_length(finalist_one_pick) <= 40),
  finalist_two_pick text check (char_length(finalist_two_pick) <= 40),
  manual_bonus_points integer check (manual_bonus_points >= 0 and manual_bonus_points <= 200),
  created_at timestamptz not null default now()
);

alter table public.participants add column if not exists champion_pick text check (char_length(champion_pick) <= 40);
alter table public.participants add column if not exists top_scorer_pick text check (char_length(top_scorer_pick) <= 60);
alter table public.participants add column if not exists runner_up_pick text check (char_length(runner_up_pick) <= 40);
alter table public.participants add column if not exists finalist_one_pick text check (char_length(finalist_one_pick) <= 40);
alter table public.participants add column if not exists finalist_two_pick text check (char_length(finalist_two_pick) <= 40);
alter table public.participants add column if not exists manual_bonus_points integer check (manual_bonus_points >= 0 and manual_bonus_points <= 200);

create unique index if not exists participants_unique_name_idx
on public.participants (lower(btrim(name)));

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  source_id text unique,
  stage text not null check (char_length(stage) between 1 and 30),
  home_team text not null check (char_length(home_team) between 1 and 40),
  away_team text not null check (char_length(away_team) between 1 and 40),
  home_score integer check (home_score between 0 and 30),
  away_score integer check (away_score between 0 and 30),
  predictions_released boolean not null default false,
  kickoff_at timestamptz,
  venue text check (char_length(venue) <= 80),
  created_at timestamptz not null default now()
);

alter table public.matches add column if not exists source_id text unique;
alter table public.matches add column if not exists predictions_released boolean not null default false;
alter table public.matches add column if not exists kickoff_at timestamptz;
alter table public.matches add column if not exists venue text check (char_length(venue) <= 80);

create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  match_id uuid not null references public.matches(id) on delete cascade,
  home_score integer not null check (home_score between 0 and 30),
  away_score integer not null check (away_score between 0 and 30),
  manual_points integer check (manual_points in (0, 1, 3)),
  reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (participant_id, match_id)
);

alter table public.predictions add column if not exists manual_points integer check (manual_points in (0, 1, 3));
alter table public.predictions add column if not exists reviewed boolean not null default false;

create table if not exists public.prediction_logs (
  id bigint generated by default as identity primary key,
  prediction_id uuid not null,
  participant_id uuid,
  match_id uuid,
  participant_name text not null,
  match_label text not null,
  home_score integer not null,
  away_score integer not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  submitted_at timestamptz not null,
  deadline_at timestamptz,
  occurred_at timestamptz not null default now()
);

alter table public.prediction_logs add column if not exists deadline_at timestamptz;

create or replace function public.log_prediction_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  prediction_row public.predictions%rowtype;
  saved_participant_name text;
  saved_match_label text;
  saved_deadline_at timestamptz;
  saved_action text;
begin
  if tg_op = 'UPDATE' and
     old.home_score = new.home_score and
     old.away_score = new.away_score then
    return new;
  end if;

  if tg_op = 'DELETE' then
    prediction_row := old;
  else
    prediction_row := new;
  end if;
  saved_action := lower(tg_op);

  select name into saved_participant_name
  from public.participants
  where id = prediction_row.participant_id;

  select home_team || ' x ' || away_team,
         kickoff_at - interval '1 minute'
  into saved_match_label, saved_deadline_at
  from public.matches
  where id = prediction_row.match_id;

  insert into public.prediction_logs (
    prediction_id, participant_id, match_id, participant_name, match_label,
    home_score, away_score, action, submitted_at, deadline_at
  ) values (
    prediction_row.id,
    prediction_row.participant_id,
    prediction_row.match_id,
    coalesce(saved_participant_name, 'Participante removido'),
    coalesce(saved_match_label, 'Jogo removido'),
    prediction_row.home_score,
    prediction_row.away_score,
    saved_action,
    prediction_row.created_at,
    saved_deadline_at
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists predictions_audit_trigger on public.predictions;
create trigger predictions_audit_trigger
after insert or update or delete on public.predictions
for each row execute function public.log_prediction_change();

insert into public.prediction_logs (
  prediction_id, participant_id, match_id, participant_name, match_label,
  home_score, away_score, action, submitted_at, deadline_at, occurred_at
)
select
  prediction.id,
  prediction.participant_id,
  prediction.match_id,
  participant.name,
  match.home_team || ' x ' || match.away_team,
  prediction.home_score,
  prediction.away_score,
  'insert',
  prediction.created_at,
  match.kickoff_at - interval '1 minute',
  prediction.created_at
from public.predictions prediction
join public.participants participant on participant.id = prediction.participant_id
join public.matches match on match.id = prediction.match_id
where not exists (
  select 1 from public.prediction_logs log
  where log.prediction_id = prediction.id and log.action = 'insert'
);

create table if not exists public.special_results (
  id boolean primary key default true,
  champion text check (char_length(champion) <= 40),
  top_scorer text check (char_length(top_scorer) <= 60),
  runner_up text check (char_length(runner_up) <= 40),
  finalist_one text check (char_length(finalist_one) <= 40),
  finalist_two text check (char_length(finalist_two) <= 40),
  bonus_active boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint single_special_results_row check (id = true)
);

alter table public.special_results add column if not exists bonus_active boolean not null default false;

insert into public.special_results (id)
values (true)
on conflict (id) do nothing;

alter table public.participants enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;
alter table public.prediction_logs enable row level security;
alter table public.special_results enable row level security;

drop policy if exists "Link pode ver participantes" on public.participants;
create policy "Link pode ver participantes" on public.participants for select to anon using (true);
drop policy if exists "Link pode adicionar participantes" on public.participants;
create policy "Link pode adicionar participantes" on public.participants for insert to anon with check (true);
drop policy if exists "Link pode editar participantes" on public.participants;
create policy "Link pode editar participantes" on public.participants for update to anon using (true) with check (true);
drop policy if exists "Link pode remover participantes" on public.participants;
create policy "Link pode remover participantes" on public.participants for delete to anon using (true);

drop policy if exists "Link pode ver jogos" on public.matches;
create policy "Link pode ver jogos" on public.matches for select to anon using (true);
drop policy if exists "Link pode adicionar jogos" on public.matches;
create policy "Link pode adicionar jogos" on public.matches for insert to anon with check (true);
drop policy if exists "Link pode atualizar resultados" on public.matches;
create policy "Link pode atualizar resultados" on public.matches for update to anon using (true) with check (true);
drop policy if exists "Link pode remover jogos" on public.matches;
create policy "Link pode remover jogos" on public.matches for delete to anon using (true);

drop policy if exists "Link pode ver palpites" on public.predictions;
create policy "Link pode ver palpites" on public.predictions for select to anon using (true);
drop policy if exists "Link pode salvar palpites" on public.predictions;
create policy "Link pode salvar palpites" on public.predictions for insert to anon with check (true);
drop policy if exists "Link pode editar palpites" on public.predictions;
create policy "Link pode editar palpites" on public.predictions for update to anon using (true) with check (true);
drop policy if exists "Link pode revisar palpites" on public.predictions;
create policy "Link pode revisar palpites" on public.predictions for update to anon using (true) with check (true);
drop policy if exists "Link pode remover palpites" on public.predictions;
create policy "Link pode remover palpites" on public.predictions for delete to anon using (true);

drop policy if exists "Link pode ver log de palpites" on public.prediction_logs;
create policy "Link pode ver log de palpites" on public.prediction_logs for select to anon using (true);

drop policy if exists "Link pode ver resultados especiais" on public.special_results;
create policy "Link pode ver resultados especiais" on public.special_results for select to anon using (true);
drop policy if exists "Link pode editar resultados especiais" on public.special_results;
create policy "Link pode editar resultados especiais" on public.special_results for update to anon using (true) with check (true);

do $$
declare
  v_table_name text;
begin
  foreach v_table_name in array array['participants', 'matches', 'predictions', 'prediction_logs', 'special_results']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = v_table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', v_table_name);
    end if;
  end loop;
end $$;

-- Classificacao mata-mata
alter table public.matches add column if not exists is_knockout boolean not null default false;
alter table public.matches add column if not exists knockout_winner text check (char_length(knockout_winner) <= 40);

create table if not exists public.passage_predictions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  match_id uuid not null references public.matches(id) on delete cascade,
  pick text not null check (char_length(pick) between 1 and 40),
  created_at timestamptz not null default now(),
  unique (participant_id, match_id)
);

alter table public.passage_predictions enable row level security;

drop policy if exists "Link pode ver passage_predictions" on public.passage_predictions;
create policy "Link pode ver passage_predictions" on public.passage_predictions for select to anon using (true);
drop policy if exists "Link pode salvar passage_predictions" on public.passage_predictions;
create policy "Link pode salvar passage_predictions" on public.passage_predictions for insert to anon with check (true);
drop policy if exists "Link pode editar passage_predictions" on public.passage_predictions;
create policy "Link pode editar passage_predictions" on public.passage_predictions for update to anon using (true) with check (true);
drop policy if exists "Link pode remover passage_predictions" on public.passage_predictions;
create policy "Link pode remover passage_predictions" on public.passage_predictions for delete to anon using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'passage_predictions'
  ) then
    alter publication supabase_realtime add table public.passage_predictions;
  end if;
end $$;
